Logging configuration
The configuration to enable logging has been added:

- Slf4j 1.7.15
- Logback 1.1.7

If you use different version of this may be you will have an exception like this:

	Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent

To see more information you can go to the official site: http://www.slf4j.org/codes.html

The `log-config.xml` contains the configuration of the loggin levels, also see the `application.yml` file to see how to configure logging for the app.